version: '3.9'

services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3309:3306"
    networks:
      - springApi-network

  spring-api:
    build: .
    environment:
      - DB_HOST=mysqldb
    ports:
      - "8090:8090"
    networks:
      - springApi-network
    depends_on:
      - mysqldb

networks:
  springApi-network:
    driver: bridge
